In [2]:
import pandas as pd
csv = "alumni liste.csv"
json ="result alumnis.json"
df = pd.read_csv(csv,sep=",")

# Create list of schools
df['Liste des écoles'] = df.apply(lambda x: ', '.join(filter(pd.notna, [x.get('linkedinSchoolName'), x.get('linkedinPreviousSchoolName')])), axis=1)

# Create list of jobs
df['Liste des jobs'] = df.apply(lambda x: ', '.join(filter(pd.notna, [x.get('linkedinJobTitle'), x.get('linkedinPreviousJobTitle')])), axis=1)

# Select and rename columns
columns_to_keep = {
    'lastName': 'Nom',
    'firstName': 'Prénom',
    'profileUrl': 'URL LinkedIn',
    'linkedinProfileImageUrl': 'Photo URL',
    'Liste des écoles': 'Liste des écoles',
    'Liste des jobs': 'Liste des jobs',
    'linkedinJobTitle': 'Poste actuel'
}

final_df = df[list(columns_to_keep.keys())].rename(columns=columns_to_keep)
final_df.head()

,Nom,Prénom,URL LinkedIn,Photo URL,Liste des écoles,Liste des jobs,Poste actuel
0,SAULT,Eric,https://www.linkedin.com/in/eric-sault-a543a029/,https://media.licdn.com/dms/image/v2/D4E03AQEY...,,"Auteur-Artiste Motion Graphic Designer, Auteur",Auteur-Artiste Motion Graphic Designer
1,Aboua,Senda,https://www.linkedin.com/in/senda-aboua-ui-ux-...,https://media.licdn.com/dms/image/v2/D4E03AQEX...,"DSP Digital School of Paris, Université Polyte...","UX UI designer, UI UX designer",UX UI designer
2,C.,THEO,https://www.linkedin.com/in/theo-c-09396123b/,https://media.licdn.com/dms/image/v2/D4D03AQHK...,"Institut Ingemedia, University of Lille 1 Scie...","Data Analyst, Apprenti chargé de statistiques ...",Data Analyst
3,Garcia,Jonathan,https://www.linkedin.com/in/jonathan-garcia-36...,https://media.licdn.com/dms/image/v2/D4D03AQFK...,"Institut Ingemedia, IUT - Université de Toulouse","Artisan d’art, Conseiller en insertion profess...",Artisan d’art
4,Destaville,Fanny,https://www.linkedin.com/in/fanny-destaville-1...,https://media.licdn.com/dms/image/v2/D5603AQH2...,Institut Ingemedia,"Hôtesse, Stagiaire communication",Hôtesse

In [3]:
df.columns

Index(['profileUrl_from_input', 'firstName', 'lastName', 'linkedinDescription',
       'linkedinFollowersCount', 'linkedinHeadline', 'linkedinIsHiringBadge',
       'linkedinIsOpenToWorkBadge', 'linkedinJobDateRange',
       'linkedinJobDescription', 'linkedinJobLocation', 'linkedinJobTitle',
       'linkedinPreviousCompanySlug', 'linkedinPreviousJobDateRange',
       'linkedinPreviousJobDescription', 'linkedinPreviousJobLocation',
       'linkedinPreviousJobTitle', 'linkedinPreviousSchoolDateRange',
       'linkedinPreviousSchoolDegree', 'linkedinPreviousSchoolDescription',
       'linkedinProfileId', 'linkedinProfileSlug', 'linkedinProfileUrl',
       'linkedinProfileUrn', 'linkedinProfileImageUrn',
       'linkedinProfileImageUrl', 'linkedinSchoolDateRange',
       'linkedinSchoolDegree', 'linkedinSchoolDescription',
       'linkedinSkillsLabel', 'location', 'previousCompanyName',
       'connectionDegree', 'refreshedAt', 'mutualConnectionsUrl',
       'connectionsUrl', 'linkedinConnectionsCount', 'profileUrl',
       'scraperProfileId', 'scraperFullName', 'companyIndustry', 'companyName',
       'companyWebsite', 'linkedinCompanyUrl', 'linkedinCompanySlug',
       'linkedinCompanyId', 'linkedinPreviousSchoolUrl',
       'linkedinPreviousSchoolCompanySlug', 'linkedinPreviousSchoolName',
       'linkedinSchoolUrl', 'linkedinSchoolCompanySlug', 'linkedinSchoolName',
       'linkedinCompanyName', 'linkedinCompanyDescription',
       'linkedinCompanyTagline', 'linkedinCompanyFollowerCount',
       'linkedinCompanyWebsite', 'linkedinCompanyEmployeesCount',
       'linkedinCompanySize', 'linkedinCompanyHeadquarter',
       'linkedinCompanyIndustry', 'linkedinCompanyFounded',
       'linkedinCompanySpecialities', 'Liste des écoles', 'Liste des jobs'],
      dtype='object')

In [4]:
df['linkedinDescription'].head() 
X = ['firstName', 'lastName', 'linkedinJobTitle','location','linkedinSchoolName','linkedinSchoolDateRange','linkedinProfileUrl','linkedinProfileImageUrl']
new_df = df[X]
new_df.to_csv('alumni.csv', index=False)

In [18]:
print(f' All : {len(new_df)}')
ingemedia_df = new_df[new_df['linkedinSchoolName'].isin(['Université de Toulon', 'Institut Ingemedia'])].copy()
ingemedia_df["promo"] = ingemedia_df["linkedinSchoolDateRange"].str[-4:]
ingemedia_df = ingemedia_df[pd.to_numeric(ingemedia_df["promo"], errors='coerce').fillna(9999) < 2026]
ingemedia_df.drop(columns=['linkedinSchoolDateRange','linkedinSchoolName'], inplace=True)
ingemedia_df.head()

 All : 1594

,firstName,lastName,linkedinJobTitle,location,linkedinProfileUrl,linkedinProfileImageUrl,promo
3,Jonathan,Garcia,Artisan d’art,"Portets, Nouvelle-Aquitaine, France",https://linkedin.com/in/jonathan-garcia-362b65357,https://media.licdn.com/dms/image/v2/D4D03AQFK...,2010
5,Marie,THIERY,"Chargée de mission ""Supports de Communication""","Strasbourg, Grand Est, France",https://linkedin.com/in/marie-thiery-b4912649,https://media.licdn.com/dms/image/v2/D4E03AQGC...,2025
6,Maureen,Crochard,Chargée de communication - Apprentie,"Toulon, Provence-Alpes-Côte d'Azur, France",https://linkedin.com/in/maureen-crochard-03281...,https://media.licdn.com/dms/image/v2/D4D03AQEN...,2025
7,Laurent,Garay,Senior Project Manager 360°,"Paris, Île-de-France, France",https://linkedin.com/in/laurent-garay-460901141,https://media.licdn.com/dms/image/v2/D4E03AQGG...,2020
13,Benjamin,Pasqualini,Chef de projet,"Provence-Alpes-Côte d'Azur, France",https://linkedin.com/in/benjamin-pasqualini-81...,https://media.licdn.com/dms/image/v2/D4D03AQFc...,2019

In [20]:
ingemedia_df = ingemedia_df.rename(columns={
    "lastName": "nom",
    "firstName": "prenom",
    "location": "lieu",
    "linkedinJobTitle": "poste",
    "linkedinPhoto": "url_photo",
    "promo": "promo",
    "linkedinProfileUrl": "profil_url"
})
ingemedia_df.head()

,prenom,nom,poste,lieu,profil_url,linkedinProfileImageUrl,promo
3,Jonathan,Garcia,Artisan d’art,"Portets, Nouvelle-Aquitaine, France",https://linkedin.com/in/jonathan-garcia-362b65357,https://media.licdn.com/dms/image/v2/D4D03AQFK...,2010
5,Marie,THIERY,"Chargée de mission ""Supports de Communication""","Strasbourg, Grand Est, France",https://linkedin.com/in/marie-thiery-b4912649,https://media.licdn.com/dms/image/v2/D4E03AQGC...,2025
6,Maureen,Crochard,Chargée de communication - Apprentie,"Toulon, Provence-Alpes-Côte d'Azur, France",https://linkedin.com/in/maureen-crochard-03281...,https://media.licdn.com/dms/image/v2/D4D03AQEN...,2025
7,Laurent,Garay,Senior Project Manager 360°,"Paris, Île-de-France, France",https://linkedin.com/in/laurent-garay-460901141,https://media.licdn.com/dms/image/v2/D4E03AQGG...,2020
13,Benjamin,Pasqualini,Chef de projet,"Provence-Alpes-Côte d'Azur, France",https://linkedin.com/in/benjamin-pasqualini-81...,https://media.licdn.com/dms/image/v2/D4D03AQFc...,2019

In [ ]:
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import time

# Initialiser le géocodeur (ajoutez un user_agent unique)
geolocator = Nominatim(user_agent="ingemedia_alumni_app")

# Rate limiter pour éviter de surcharger le service (1 requête par seconde)
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)

def get_coordinates(lieu):
    try:
        if pd.isna(lieu) or lieu == "":
            return None, None
        location = geocode(lieu)
        if location:
            return location.latitude, location.longitude
        return None, None
    except Exception as e:
        print(f"Erreur pour '{lieu}': {e}")
        return None, None

# Appliquer la fonction sur la colonne 'lieu'
ingemedia_df[["latitude", "longitude"]] = ingemedia_df["lieu"].apply(
    lambda x: pd.Series(get_coordinates(x))
)

ingemedia_df.head()