In [187]:
import pandas as pd 

xls = pd.ExcelFile('etudiants-ingemedia.xlsx')

df_2008 = pd.read_excel(xls, sheet_name='2007-2008')
df_2008['promotion'] = '2008'
df_2009 = pd.read_excel(xls, sheet_name='2008-2009')
df_2009['promotion'] = '2009'
df_2010 = pd.read_excel(xls, sheet_name='2009-2010')
df_2010['promotion'] = '2010'
df_2011 = pd.read_excel(xls, sheet_name='2010-2011')
df_2011['promotion'] = '2011'
df_2012 = pd.read_excel(xls, sheet_name='2011-2012')
df_2012['promotion'] = '2012'
df_2013 = pd.read_excel(xls, sheet_name='2012-2013')
df_2013['promotion'] = '2013'
df_2014 = pd.read_excel(xls, sheet_name='2013-2014')
df_2014['promotion'] = '2014'
df_2015 = pd.read_excel(xls, sheet_name='2014-2015')
df_2015['promotion'] = '2015'
df_2016 = pd.read_excel(xls, sheet_name='2015-2016')
df_2016['promotion'] = '2016'
df_2017 = pd.read_excel(xls, sheet_name='2016-2017')
df_2017['promotion'] = '2017'
df_2018 = pd.read_excel(xls, sheet_name='2017-2018')
df_2018['promotion'] = '2018'
df_2019 = pd.read_excel(xls, sheet_name='2018-2019')
df_2019['promotion'] = '2019'
df_2020 = pd.read_excel(xls, sheet_name='2019-2020')
df_2020['promotion'] = '2020'
df_2021 = pd.read_excel(xls, sheet_name='2020-2021')
df_2021['promotion'] = '2021'
df_2022 = pd.read_excel(xls, sheet_name='2021-2022')
df_2022['promotion'] = '2022'
df_2023 = pd.read_excel(xls, sheet_name='2022-2023')
df_2023['promotion'] = '2023'
df_2024 = pd.read_excel(xls, sheet_name='2023-2024')
df_2024['promotion'] = '2024'

In [188]:
df_all = pd.concat([df_2008, df_2009, df_2010, df_2011, df_2012, df_2013, df_2014, df_2015, df_2016, df_2017, df_2018, df_2019, df_2020, df_2021, df_2022, df_2023, df_2024], ignore_index=True)
df_all.head(10)

,Formation,etudiants_nom,promotion,intitule_etudiant,nom_etudiant
0,NaN,"LEBEUX, FRANÇOIS",2008,NaN,NaN
1,NaN,"TIXIER LAMAISON, THOMAS",2008,NaN,NaN
2,NaN,"LABROUSSE, FABIENNE",2008,NaN,NaN
3,NaN,"SEGUIN-CADICHE,STEPHANIE",2008,NaN,NaN
4,NaN,"GANFOUD, AYMEN",2008,NaN,NaN
5,NaN,"MEKKI, RAKIA",2008,NaN,NaN
6,NaN,"JULLIAND, NICOLAS",2008,NaN,NaN
7,NaN,"FRANCAIS, TARDY, VALERIE",2008,NaN,NaN
8,NaN,"BORYS, STANISLAS",2008,NaN,NaN
9,NaN,"CARRILLON, REMY",2008,NaN,NaN

In [189]:
df_all_cleaned = df_all.copy()
df_all_cleaned = df_all_cleaned.drop(columns=['Formation'])
# Prendre la première valeur non-nulle entre les deux colonnes
df_all_cleaned['nom_entier'] = df_all_cleaned['etudiants_nom'].fillna(df_all_cleaned['nom_etudiant'])

# Supprimer tout ce qui est entre parenthèses (ex: "(NTS)")
df_all_cleaned['nom_entier'] = df_all_cleaned['nom_entier'].str.replace(r'\s*\([^)]*\)', '', regex=True).str.strip()


# Si virgule : séparer par ',', sinon par espace
df_all_cleaned['nom'] = df_all_cleaned['nom_entier'].apply(
    lambda x: x.split(',')[0].strip() if ',' in str(x) else str(x).split(' ')[-1]
)

df_all_cleaned['prenom'] = df_all_cleaned['nom_entier'].apply(
    lambda x: x.split(',')[1].strip() if ',' in str(x) else str(x).split(' ')[0]
)

df_all_cleaned = df_all_cleaned.drop(columns=['etudiants_nom', 'nom_etudiant','intitule_etudiant','nom_entier'])

df_all_cleaned.head(10)

  promotion              nom     prenom
0      2008           LEBEUX   FRANÇOIS
1      2008  TIXIER LAMAISON     THOMAS
2      2008        LABROUSSE   FABIENNE
3      2008   SEGUIN-CADICHE  STEPHANIE
4      2008          GANFOUD      AYMEN
5      2008            MEKKI      RAKIA
6      2008         JULLIAND    NICOLAS
7      2008         FRANCAIS      TARDY
8      2008            BORYS  STANISLAS
9      2008        CARRILLON       REMY

In [190]:
liste_etudiants.shape

(6299, 3)

In [191]:
liste_etudiants = df_all_cleaned.copy()
liste_etudiants.describe()

       promotion    nom  prenom
count       6299   6299    6299
unique        17   3390    2141
top         2009  DAVID  THOMAS
freq         680     24      70

In [192]:
liste_etudiants.isnull().sum()

promotion    0
nom          0
prenom       0
dtype: int64

In [193]:
# Vérifier les doublons en considérant nom + prenom ensemble
nb_doublons = df_all_cleaned.duplicated(subset=['nom', 'prenom']).sum()
print(f"Nombre de doublons (nom + prenom) : {nb_doublons}")

# Afficher les doublons
print("\nLignes en doublon :")
doublons = df_all_cleaned[df_all_cleaned.duplicated(subset=['nom', 'prenom'], keep=False)]
doublons.sort_values(by=['nom', 'prenom']).head(20)

Nombre de doublons (nom + prenom) : 2281

Lignes en doublon :

     promotion               nom          prenom
5296      2022  ABASS MADO ABARI        HABSATOU
5773      2023  ABASS MADO ABARI        HABSATOU
6129      2024  ABASS MADO ABARI        HABSATOU
3066      2016            ABBACI           LINDA
3523      2017            ABBACI           LINDA
3979      2018            ABBACI           LINDA
3086      2016         ABD RAZAK  DJABIR ADEBAYO
3578      2017         ABD RAZAK  DJABIR ADEBAYO
3980      2018         ABD RAZAK  DJABIR ADEBAYO
4295      2019         ABD RAZAK  DJABIR ADEBAYO
5741      2023          ABDALLAH         HADIDJA
6097      2024          ABDALLAH         HADIDJA
383       2009         ABDENNABI           KARIM
1318      2010         ABDENNABI           KARIM
1617      2011            ABELLA           CYRIL
2106      2012            ABELLA           CYRIL
1512      2011             ABIDI            ANIS
1893      2012             ABIDI            ANIS
2793      2015              ABLA         CHERYNE
3302      2016              ABLA         CHERYNE

In [194]:
# Supprimer les doublons
# keep='first' : garde la première occurrence
# keep='last' : garde la dernière occurrence
# keep=False : supprime tous les doublons

df_all_cleaned = df_all_cleaned.drop_duplicates(subset=['nom', 'prenom'], keep='first')

print(f"Nombre de lignes après suppression des doublons : {len(df_all_cleaned)}")
df_all_cleaned.head(10)

Nombre de lignes après suppression des doublons : 4018

  promotion              nom     prenom
0      2008           LEBEUX   FRANÇOIS
1      2008  TIXIER LAMAISON     THOMAS
2      2008        LABROUSSE   FABIENNE
3      2008   SEGUIN-CADICHE  STEPHANIE
4      2008          GANFOUD      AYMEN
5      2008            MEKKI      RAKIA
6      2008         JULLIAND    NICOLAS
7      2008         FRANCAIS      TARDY
8      2008            BORYS  STANISLAS
9      2008        CARRILLON       REMY

In [195]:
df_all_cleaned.to_csv('liste_etudiants_ingemedia_cleaned.csv', index=False)

In [196]:
# Installer ddgs si nécessaire
# !pip install ddgs

from ddgs import DDGS
import time

# Charger le CSV nettoyé
df = pd.read_csv('liste_etudiants_ingemedia_cleaned.csv')
print(f"Nombre d'étudiants : {len(df)}")
df.head()

Nombre d'étudiants : 4018

   promotion              nom     prenom
0       2008           LEBEUX   FRANÇOIS
1       2008  TIXIER LAMAISON     THOMAS
2       2008        LABROUSSE   FABIENNE
3       2008   SEGUIN-CADICHE  STEPHANIE
4       2008          GANFOUD      AYMEN

In [197]:
df['search'] = df.apply(
    lambda row: f"\"{row['nom']} {row['prenom']}\" AND (Université de Toulon OR Ingemedia)",
    axis=1
)

df.head()

,promotion,nom,prenom,search
0,2008,LEBEUX,FRANÇOIS,"""LEBEUX FRANÇOIS"" AND (Université de Toulon OR..."
1,2008,TIXIER LAMAISON,THOMAS,"""TIXIER LAMAISON THOMAS"" AND (Université de To..."
2,2008,LABROUSSE,FABIENNE,"""LABROUSSE FABIENNE"" AND (Université de Toulon..."
3,2008,SEGUIN-CADICHE,STEPHANIE,"""SEGUIN-CADICHE STEPHANIE"" AND (Université de ..."
4,2008,GANFOUD,AYMEN,"""GANFOUD AYMEN"" AND (Université de Toulon OR I..."

In [198]:
# Exporter le fichier complet + 4 fichiers en quarts (sans FutureWarning)
import numpy as np

# Sauvegarder le fichier complet
df.to_csv('liste_etudiants_and_search.csv', index=False, encoding='utf-8')
print("Fichier complet écrit: liste_etudiants_and_search.csv")

# Découper via l'index pour éviter l'utilisation de swapaxes
index_parts = np.array_split(df.index.to_numpy(), 4)
for i, idx in enumerate(index_parts, start=1):
    part = df.loc[idx]
    out_name = f'liste_etudiants_and_search_part{i}.csv'
    part.to_csv(out_name, index=False, encoding='utf-8')
    print(f"Part {i} écrite: {out_name} (lignes: {len(part)})")

Fichier complet écrit: liste_etudiants_and_search.csv
Part 1 écrite: liste_etudiants_and_search_part1.csv (lignes: 1005)
Part 2 écrite: liste_etudiants_and_search_part2.csv (lignes: 1005)
Part 3 écrite: liste_etudiants_and_search_part3.csv (lignes: 1004)
Part 4 écrite: liste_etudiants_and_search_part4.csv (lignes: 1004)