In [2]:
import pandas as pd 
alumni_df = pd.read_csv('alumnis_export_20260120_134911.csv', encoding='utf-8')
alumni_df.head()

,ID,Nom,Prénom,Ville,Poste,LinkedIn,Promo,Latitude,Longitude,Entreprise
0,1,Garcia,Jonathan,Portets,Artisan d’art,https://linkedin.com/in/jonathan-garcia-362b65357,2010,44.695969,-0.423824,Soleil Verre
1,2,THIERY,Marie,Strasbourg,"Chargée de mission ""Supports de Communication""",https://linkedin.com/in/marie-thiery-b4912649,2025,48.584614,7.750713,ARTE
2,3,Crochard,Maureen,Toulon,Chargée de communication - Apprentie,https://linkedin.com/in/maureen-crochard-03281...,2025,43.125731,5.930492,Université de Toulon
3,4,Garay,Laurent,Paris,Senior Project Manager 360°,https://linkedin.com/in/laurent-garay-460901141,2020,48.858890,2.320041,TBWA Paris
4,5,Pasqualini,Benjamin,Mirabeau,Chef de projet,https://linkedin.com/in/benjamin-pasqualini-81...,2019,44.058056,6.063851,PETRA PATRIMONIA

In [25]:
# Récupérer les entreprises et compter les occurrences
# Exclure "Aucune"

enterprise_df = alumni_df[alumni_df['Entreprise'] != 'Aucune']
enterprise_df = enterprise_df.groupby('Entreprise').size().reset_index(name='nombre')
enterprise_df = enterprise_df.sort_values('nombre', ascending=False).reset_index(drop=True)
enterprise_df.columns = ['nom', 'nombre']

print(f"Nombre d'entreprises uniques : {len(enterprise_df)}")
enterprise_df.head(20)

Nombre d'entreprises uniques : 721

                                nom  nombre
0                   Orange Business       6
1                  Marine Nationale       5
2                           STRATIS       4
3              Université de Toulon       4
4                           L'Oréal       3
5                               CGI       3
6                         Freelance       3
7          COMMLAB Marine nationale       3
8                            Airbus       3
9                            Swello       3
10     Toulon Provence Méditerranée       3
11                         WiziShop       3
12                        DDB Paris       2
13      DigitecPharma by IntecMedia       2
14  CPAM du Var (Assurance Maladie)       2
15                            ALTEN       2
16                   Foster Academy       2
17           Icademie International       2
18                     Leboncoin.fr       2
19                             MANE       2

## Scraping Orange Business

In [26]:
import requests
from bs4 import BeautifulSoup

def get_sitemap_urls(sitemap_url):
    """Récupère les URLs des sitemaps enfants à partir du sitemap_index"""
    try:
        response = requests.get(sitemap_url)
        soup = BeautifulSoup(response.content, 'xml')
        urls = [loc.text for loc in soup.find_all('loc')]
        return urls
    except Exception as e:
        print(f"Erreur en récupérant {sitemap_url}: {e}")
        return []

def get_job_urls(sitemap_url):
    """Récupère les URLs des offres d'emploi à partir d'un sitemap"""
    try:
        response = requests.get(sitemap_url)
        soup = BeautifulSoup(response.content, 'xml')
        urls = [loc.text for loc in soup.find_all('loc')]
        job_urls = [u for u in urls if '/job/' in u or '/offres/' in u]
        return job_urls
    except Exception as e:
        print(f"Erreur en récupérant {sitemap_url}: {e}")
        return []

# Récupérer le sitemap_index
sitemap_index = "https://orange.jobs/fr/fr/sitemap_index.xml"
sitemap_urls = get_sitemap_urls(sitemap_index)

print(f"Nombre de sitemaps trouvés : {len(sitemap_urls)}")

# Récupérer toutes les offres d'emploi
all_job_urls = []
for sitemap_url in sitemap_urls:
    print(f"Traitement : {sitemap_url}")
    job_urls = get_job_urls(sitemap_url)
    all_job_urls.extend(job_urls)
    print(f"  -> {len(job_urls)} offres trouvées")

print(f"\nTotal d'offres d'emploi : {len(all_job_urls)}")

# Créer un DataFrame avec les URLs
orange_jobs_df = pd.DataFrame({'url': all_job_urls})

print(f"Nombre d'offres uniques : {len(orange_jobs_df)}")
print(f"\nDataFrame créé :")
orange_jobs_df.head(10)

Nombre de sitemaps trouvés : 2
Traitement : https://orange.jobs/fr/fr/sitemap1.xml
  -> 500 offres trouvées
Traitement : https://orange.jobs/fr/fr/sitemap2.xml
  -> 385 offres trouvées

Total d'offres d'emploi : 885
Nombre d'offres uniques : 885

DataFrame créé :

                                                 url
0  https://orange.jobs/fr/fr/job/CTS-2025-47627/S...
1  https://orange.jobs/fr/fr/job/CTS-2025-45465/C...
2  https://orange.jobs/fr/fr/job/CTS-2025-43229/O...
3  https://orange.jobs/fr/fr/job/CTS-2025-46623/I...
4  https://orange.jobs/fr/fr/job/CTS-2023-26884/S...
5  https://orange.jobs/fr/fr/job/CTS-2025-47360/S...
6  https://orange.jobs/fr/fr/job/CTS-2025-47636/A...
7  https://orange.jobs/fr/fr/job/CTS-2025-47792/T...
8  https://orange.jobs/fr/fr/job/CTS-2025-46612/S...
9  https://orange.jobs/fr/fr/job/CTS-2025-47609/I...

In [27]:
import json

url = "https://orange.jobs/fr/fr/job/CTS-2025-47112/Stage-OW-OWF-Conseiller-Client-Back-Office-F-H"

def scrap_orange_job(url):
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    }
    
    try:
        response = requests.get(url, headers=headers)
        if response.status_code != 200:
            return f"Erreur {response.status_code}"
    except Exception as e:
        return f"Erreur de connexion : {e}"

    soup = BeautifulSoup(response.text, 'html.parser')

    # 1. Extraction du script JSON-LD
    json_script = soup.find('script', type='application/ld+json')
    
    if json_script:
        try:
            data = json.loads(json_script.string)
        except Exception as e:
            return f"Erreur parsing JSON : {e}"
        
        # 2. Préparation des données spécifiques avec gestion des listes
        try:
            job_location = data.get('jobLocation', {})
            if isinstance(job_location, list) and job_location:
                job_location = job_location[0]
            address_data = job_location.get('address', {}) if isinstance(job_location, dict) else {}
        except Exception as e:
            print(f"Erreur sur jobLocation pour {url} : {e}")
            return f"Erreur jobLocation : {e}"
        
        # Nettoyage du HTML pour le texte brut
        raw_description = data.get("description", "")
        clean_text = BeautifulSoup(raw_description, "html.parser").get_text(separator="\n").strip()

        # 3. Construction du dictionnaire final avec protection d'erreur
        try:
            job_info = {
                "Titre": data.get("title"),
                "Date de publication": data.get("datePosted"),
                "ID": data.get("identifier", {}).get("value"),
                
                # Localisation
                "Ville": address_data.get("addressLocality"),
                "Pays": address_data.get("addressCountry"),
                
                # Contenu
                "Texte": data.get("description"),
                "Lien Original": url
            }
            return job_info
        except Exception as e:
            print(f"Erreur lors de la construction du dictionnaire pour {url} : {e}")
            return f"Erreur construction dictionnaire : {e}"

    return "Données JSON non trouvées sur la page"

# --- Exécution du test ---
offre = scrap_orange_job(url)

if isinstance(offre, dict):
    print("--- RÉSULTAT DU SCRAPING ---")
    for cle, valeur in offre.items():
        if cle == "Texte":
            # On affiche seulement les 150 premiers caractères pour ne pas polluer l'écran
            print(f"{cle}: {valeur[:150]}...") 
        else:
            print(f"{cle}: {valeur}")
else:
    print(offre)

--- RÉSULTAT DU SCRAPING ---
Titre: Stage - OW/OWF Conseiller Client Back Office F/H
Date de publication: 2026-01-20
ID: CTS-2025-47112
Ville: TOULON
Pays: FRANCE
Texte: &lt;p&gt;&lt;strong&gt;Date de publication :&lt;/strong&gt; Oct 29, 2025, 3:55PM&lt;/p&gt;&lt;p&gt;Ø Participe à l'évolution du SI : Ecrit/réalise les...
Lien Original: https://orange.jobs/fr/fr/job/CTS-2025-47112/Stage-OW-OWF-Conseiller-Client-Back-Office-F-H

In [28]:
import time
import random

# Appliquer le scraping sur toutes les offres et enrichir le DataFrame
job_rows = []
errors = []
total = len(orange_jobs_df)
print(f"Début du scraping : {total} offres")

for idx, url in enumerate(orange_jobs_df['url'], start=1):
    info = scrap_orange_job(url)
    if isinstance(info, dict):
        info['url'] = url  # conserver la clé de jointure
        job_rows.append(info)
        status_msg = "OK"
    else:
        errors.append({'url': url, 'erreur': info})
        if isinstance(info, str) and '410' in info:
            status_msg = "Erreur 410"
        else:
            status_msg = f"Erreur: {info}"
            print(f"Erreur de scraping pour {url} -> {info}")
    
    print(f"Progression : {idx}/{total} | {status_msg}")

    time.sleep(random.uniform(1, 3))

orange_jobs_details = pd.DataFrame(job_rows)
orange_jobs_full = orange_jobs_df.merge(orange_jobs_details, on='url', how='left')

print(f"Offres enrichies : {len(orange_jobs_details)} / {len(orange_jobs_df)}")
print(f"Erreurs : {len(errors)}")
orange_jobs_full.head()

Début du scraping : 885 offres
Progression : 1/885 | OK
Progression : 2/885 | Erreur 410
Progression : 3/885 | OK
Progression : 4/885 | Erreur 410
Progression : 5/885 | Erreur 410
Progression : 6/885 | OK
Progression : 7/885 | Erreur 410
Progression : 8/885 | Erreur 410
Progression : 9/885 | OK
Progression : 10/885 | Erreur 410
Progression : 11/885 | Erreur 410
Progression : 12/885 | Erreur 410
Progression : 13/885 | OK
Progression : 14/885 | Erreur 410
Progression : 15/885 | Erreur 410
Progression : 16/885 | OK
Progression : 17/885 | Erreur 410
Progression : 18/885 | OK
Progression : 19/885 | Erreur 410
Progression : 20/885 | Erreur 410
Progression : 21/885 | Erreur 410
Progression : 22/885 | Erreur 410
Progression : 23/885 | Erreur 410
Progression : 24/885 | Erreur 410
Progression : 25/885 | Erreur 410
Progression : 26/885 | OK
Progression : 27/885 | Erreur 410
Progression : 28/885 | OK
Progression : 29/885 | Erreur 410
Progression : 30/885 | Erreur 410
Progression : 31/885 | Erreur 410
Progression : 32/885 | Erreur 410
Progression : 33/885 | Erreur 410
Progression : 34/885 | OK
Progression : 35/885 | Erreur 410
Progression : 36/885 | Erreur 410
Progression : 37/885 | Erreur 410
Progression : 38/885 | OK
Progression : 39/885 | OK
Progression : 40/885 | OK
Progression : 41/885 | OK
Progression : 42/885 | Erreur 410
Progression : 43/885 | OK
Progression : 44/885 | OK
Progression : 45/885 | Erreur 410
Progression : 46/885 | Erreur 410
Progression : 47/885 | Erreur 410
Progression : 48/885 | Erreur 410
Progression : 49/885 | Erreur 410
Progression : 50/885 | Erreur 410
Progression : 51/885 | Erreur 410
Progression : 52/885 | OK
Progression : 53/885 | Erreur 410
Progression : 54/885 | Erreur 410
Progression : 55/885 | Erreur 410
Progression : 56/885 | Erreur 410
Progression : 57/885 | Erreur 410
Progression : 58/885 | Erreur 410
Progression : 59/885 | Erreur 410
Progression : 60/885 | Erreur 410
Progression : 61/885 | Erreur 410
Progression : 62/885 | Erreur 410
Progression : 63/885 | OK
Progression : 64/885 | Erreur 410
Progression : 65/885 | Erreur 410
Progression : 66/885 | OK
Progression : 67/885 | OK
Progression : 68/885 | Erreur 410
Progression : 69/885 | OK
Progression : 70/885 | Erreur 410
Progression : 71/885 | Erreur 410
Progression : 72/885 | Erreur 410
Progression : 73/885 | Erreur 410
Progression : 74/885 | Erreur 410
Progression : 75/885 | Erreur 410
Progression : 76/885 | Erreur 410
Progression : 77/885 | OK
Progression : 78/885 | Erreur 410
Progression : 79/885 | OK
Progression : 80/885 | OK
Progression : 81/885 | Erreur 410
Progression : 82/885 | Erreur 410
Progression : 83/885 | Erreur 410
Progression : 84/885 | Erreur 410
Progression : 85/885 | Erreur 410
Progression : 86/885 | Erreur 410
Progression : 87/885 | Erreur 410
Progression : 88/885 | OK
Progression : 89/885 | Erreur 410
Progression : 90/885 | OK
Progression : 91/885 | Erreur 410
Progression : 92/885 | Erreur 410
Progression : 93/885 | OK
Progression : 94/885 | Erreur 410
Progression : 95/885 | OK
Progression : 96/885 | OK
Progression : 97/885 | OK
Progression : 98/885 | OK
Progression : 99/885 | Erreur 410
Progression : 100/885 | Erreur 410
Progression : 101/885 | OK
Progression : 102/885 | Erreur 410
Progression : 103/885 | OK
Progression : 104/885 | OK
Progression : 105/885 | Erreur 410
Progression : 106/885 | OK
Progression : 107/885 | Erreur 410
Progression : 108/885 | OK
Progression : 109/885 | Erreur 410
Progression : 110/885 | Erreur 410
Progression : 111/885 | Erreur 410
Progression : 112/885 | OK
Progression : 113/885 | OK
Progression : 114/885 | Erreur 410
Progression : 115/885 | Erreur 410
Progression : 116/885 | OK
Progression : 117/885 | Erreur 410
Progression : 118/885 | OK
Progression : 119/885 | OK
Progression : 120/885 | OK
Progression : 121/885 | OK
Progression : 122/885 | Erreur 410
Progression : 123/885 | Erreur 410
Progression : 124/885 | Erreur 410
Progression : 125/885 | OK
Progression : 126/885 | Erreur 410
Progression : 127/885 | OK
Progression : 128/885 | OK
Progression : 129/885 | OK
Progression : 130/885 | Erreur 410
Progression : 131/885 | OK
Progression : 132/885 | OK
Progression : 133/885 | OK
Progression : 134/885 | OK
Progression : 135/885 | OK
Progression : 136/885 | OK
Progression : 137/885 | OK
Progression : 138/885 | OK
Progression : 139/885 | OK
Progression : 140/885 | OK
Progression : 141/885 | OK
Progression : 142/885 | OK
Progression : 143/885 | OK
Progression : 144/885 | OK
Progression : 145/885 | OK
Progression : 146/885 | OK
Progression : 147/885 | OK
Progression : 148/885 | OK
Progression : 149/885 | OK
Progression : 150/885 | OK
Progression : 151/885 | OK
Progression : 152/885 | OK
Progression : 153/885 | OK
Progression : 154/885 | OK
Progression : 155/885 | OK
Progression : 156/885 | OK
Progression : 157/885 | OK
Progression : 158/885 | OK
Progression : 159/885 | OK
Progression : 160/885 | OK
Progression : 161/885 | OK
Progression : 162/885 | OK
Progression : 163/885 | OK
Progression : 164/885 | OK
Progression : 165/885 | OK
Progression : 166/885 | OK
Progression : 167/885 | OK
Progression : 168/885 | OK
Progression : 169/885 | OK
Progression : 170/885 | OK
Progression : 171/885 | OK
Progression : 172/885 | OK
Progression : 173/885 | OK
Progression : 174/885 | OK
Progression : 175/885 | OK
Progression : 176/885 | OK
Progression : 177/885 | OK
Progression : 178/885 | OK
Progression : 179/885 | OK
Progression : 180/885 | OK
Progression : 181/885 | OK
Progression : 182/885 | OK
Progression : 183/885 | OK
Progression : 184/885 | OK
Progression : 185/885 | OK
Progression : 186/885 | OK
Progression : 187/885 | OK
Progression : 188/885 | OK
Progression : 189/885 | OK
Progression : 190/885 | OK
Progression : 191/885 | OK
Progression : 192/885 | OK
Progression : 193/885 | OK
Progression : 194/885 | OK
Progression : 195/885 | OK
Progression : 196/885 | OK
Progression : 197/885 | OK
Progression : 198/885 | OK
Progression : 199/885 | OK
Progression : 200/885 | OK
Progression : 201/885 | OK
Progression : 202/885 | OK
Progression : 203/885 | OK
Progression : 204/885 | OK
Progression : 205/885 | OK
Progression : 206/885 | OK
Progression : 207/885 | OK
Progression : 208/885 | OK
Progression : 209/885 | OK
Progression : 210/885 | OK
Progression : 211/885 | OK
Progression : 212/885 | OK
Progression : 213/885 | OK
Progression : 214/885 | OK
Progression : 215/885 | OK
Progression : 216/885 | OK
Progression : 217/885 | OK
Progression : 218/885 | OK
Progression : 219/885 | OK
Progression : 220/885 | OK
Progression : 221/885 | OK
Progression : 222/885 | OK
Progression : 223/885 | OK
Progression : 224/885 | OK
Progression : 225/885 | OK
Progression : 226/885 | OK
Progression : 227/885 | OK
Progression : 228/885 | OK
Progression : 229/885 | OK
Progression : 230/885 | OK
Progression : 231/885 | OK
Progression : 232/885 | OK
Progression : 233/885 | OK
Progression : 234/885 | OK
Progression : 235/885 | OK
Progression : 236/885 | OK
Progression : 237/885 | OK
Progression : 238/885 | OK
Progression : 239/885 | OK
Progression : 240/885 | OK
Progression : 241/885 | OK
Progression : 242/885 | OK
Progression : 243/885 | OK
Progression : 244/885 | OK
Progression : 245/885 | OK
Progression : 246/885 | OK
Progression : 247/885 | OK
Progression : 248/885 | OK
Progression : 249/885 | OK
Progression : 250/885 | OK
Progression : 251/885 | OK
Progression : 252/885 | OK
Progression : 253/885 | OK
Progression : 254/885 | OK
Progression : 255/885 | OK
Progression : 256/885 | OK
Progression : 257/885 | OK
Progression : 258/885 | OK
Progression : 259/885 | OK
Progression : 260/885 | OK
Progression : 261/885 | OK
Progression : 262/885 | OK
Progression : 263/885 | OK
Progression : 264/885 | OK
Progression : 265/885 | OK
Progression : 266/885 | OK
Progression : 267/885 | OK
Progression : 268/885 | OK
Progression : 269/885 | OK
Progression : 270/885 | OK
Progression : 271/885 | OK
Progression : 272/885 | OK
Progression : 273/885 | OK
Progression : 274/885 | OK
Progression : 275/885 | OK
Progression : 276/885 | OK
Progression : 277/885 | OK
Progression : 278/885 | OK
Progression : 279/885 | OK
Progression : 280/885 | OK
Progression : 281/885 | OK
Progression : 282/885 | OK
Progression : 283/885 | OK
Progression : 284/885 | OK
Progression : 285/885 | OK
Progression : 286/885 | OK
Progression : 287/885 | OK
Progression : 288/885 | OK
Progression : 289/885 | OK
Progression : 290/885 | OK
Progression : 291/885 | OK
Progression : 292/885 | OK
Progression : 293/885 | OK
Progression : 294/885 | OK
Progression : 295/885 | OK
Progression : 296/885 | OK
Progression : 297/885 | OK
Progression : 298/885 | OK
Progression : 299/885 | OK
Progression : 300/885 | OK
Progression : 301/885 | OK
Progression : 302/885 | OK
Progression : 303/885 | OK
Progression : 304/885 | Erreur 410
Progression : 305/885 | OK
Progression : 306/885 | OK
Progression : 307/885 | Erreur 410
Progression : 308/885 | Erreur 410
Progression : 309/885 | Erreur 410
Progression : 310/885 | Erreur 410
Progression : 311/885 | Erreur 410
Progression : 312/885 | OK
Progression : 313/885 | OK
Progression : 314/885 | Erreur 410
Progression : 315/885 | Erreur 410
Progression : 316/885 | Erreur 410
Progression : 317/885 | Erreur 410
Progression : 318/885 | OK
Progression : 319/885 | Erreur 410
Progression : 320/885 | OK
Progression : 321/885 | OK
Progression : 322/885 | OK
Progression : 323/885 | Erreur 410
Progression : 324/885 | OK
Progression : 325/885 | Erreur 410
Progression : 326/885 | Erreur 410
Progression : 327/885 | Erreur 410
Progression : 328/885 | Erreur 410
Progression : 329/885 | Erreur 410
Progression : 330/885 | Erreur 410
Progression : 331/885 | Erreur 410
Progression : 332/885 | OK
Progression : 333/885 | Erreur 410
Progression : 334/885 | Erreur 410
Progression : 335/885 | Erreur 410
Progression : 336/885 | Erreur 410
Progression : 337/885 | Erreur 410
Progression : 338/885 | Erreur 410
Progression : 339/885 | Erreur 410
Progression : 340/885 | Erreur 410
Progression : 341/885 | OK
Progression : 342/885 | Erreur 410
Progression : 343/885 | OK
Progression : 344/885 | Erreur 410
Progression : 345/885 | Erreur 410
Progression : 346/885 | Erreur 410
Progression : 347/885 | Erreur 410
Progression : 348/885 | Erreur 410
Progression : 349/885 | OK
Progression : 350/885 | Erreur 410
Progression : 351/885 | Erreur 410
Progression : 352/885 | OK
Progression : 353/885 | OK
Progression : 354/885 | Erreur 410
Progression : 355/885 | Erreur 410
Progression : 356/885 | Erreur 410
Progression : 357/885 | OK
Progression : 358/885 | Erreur 410
Progression : 359/885 | Erreur 410
Progression : 360/885 | Erreur 410
Progression : 361/885 | Erreur 410
Progression : 362/885 | Erreur 410
Progression : 363/885 | OK
Progression : 364/885 | Erreur 410
Progression : 365/885 | OK
Progression : 366/885 | OK
Progression : 367/885 | Erreur 410
Progression : 368/885 | Erreur 410
Progression : 369/885 | Erreur 410
Progression : 370/885 | OK
Progression : 371/885 | OK
Progression : 372/885 | OK
Progression : 373/885 | OK
Progression : 374/885 | Erreur 410
Progression : 375/885 | Erreur 410
Progression : 376/885 | Erreur 410
Progression : 377/885 | OK
Progression : 378/885 | OK
Progression : 379/885 | Erreur 410
Progression : 380/885 | Erreur 410
Progression : 381/885 | Erreur 410
Progression : 382/885 | OK
Progression : 383/885 | OK
Progression : 384/885 | OK
Progression : 385/885 | Erreur 410
Progression : 386/885 | Erreur 410
Progression : 387/885 | OK
Progression : 388/885 | Erreur 410
Progression : 389/885 | OK
Progression : 390/885 | Erreur 410
Progression : 391/885 | Erreur 410
Progression : 392/885 | OK
Progression : 393/885 | Erreur 410
Progression : 394/885 | OK
Progression : 395/885 | Erreur 410
Progression : 396/885 | Erreur 410
Progression : 397/885 | Erreur 410
Progression : 398/885 | Erreur 410
Progression : 399/885 | Erreur 410
Progression : 400/885 | Erreur 410
Progression : 401/885 | OK
Progression : 402/885 | OK
Progression : 403/885 | OK
Progression : 404/885 | Erreur 410
Progression : 405/885 | OK
Progression : 406/885 | Erreur 410
Progression : 407/885 | Erreur 410
Progression : 408/885 | Erreur 410
Progression : 409/885 | Erreur 410
Progression : 410/885 | OK
Progression : 411/885 | Erreur 410
Progression : 412/885 | Erreur 410
Progression : 413/885 | OK
Progression : 414/885 | OK
Progression : 415/885 | OK
Progression : 416/885 | OK
Progression : 417/885 | OK
Progression : 418/885 | OK
Progression : 419/885 | Erreur 410
Progression : 420/885 | OK
Progression : 421/885 | OK
Progression : 422/885 | OK
Progression : 423/885 | OK
Progression : 424/885 | OK
Progression : 425/885 | OK
Progression : 426/885 | OK
Progression : 427/885 | OK
Progression : 428/885 | OK
Progression : 429/885 | OK
Progression : 430/885 | OK
Progression : 431/885 | OK
Progression : 432/885 | OK
Progression : 433/885 | OK
Progression : 434/885 | OK
Progression : 435/885 | OK
Progression : 436/885 | OK
Progression : 437/885 | OK
Progression : 438/885 | OK
Progression : 439/885 | OK
Progression : 440/885 | OK
Progression : 441/885 | OK
Progression : 442/885 | OK
Progression : 443/885 | OK
Progression : 444/885 | OK
Progression : 445/885 | OK
Progression : 446/885 | OK
Progression : 447/885 | OK
Progression : 448/885 | OK
Progression : 449/885 | OK
Progression : 450/885 | OK
Progression : 451/885 | OK
Progression : 452/885 | OK
Progression : 453/885 | OK
Progression : 454/885 | OK
Progression : 455/885 | OK
Progression : 456/885 | OK
Progression : 457/885 | OK
Progression : 458/885 | OK
Progression : 459/885 | OK
Progression : 460/885 | OK
Progression : 461/885 | OK
Progression : 462/885 | OK
Progression : 463/885 | OK
Progression : 464/885 | OK
Progression : 465/885 | OK
Progression : 466/885 | OK
Progression : 467/885 | OK
Progression : 468/885 | OK
Progression : 469/885 | OK
Progression : 470/885 | OK
Progression : 471/885 | OK
Progression : 472/885 | OK
Progression : 473/885 | OK
Progression : 474/885 | OK
Progression : 475/885 | OK
Progression : 476/885 | OK
Progression : 477/885 | OK
Progression : 478/885 | OK
Progression : 479/885 | OK
Progression : 480/885 | OK
Progression : 481/885 | OK
Progression : 482/885 | OK
Progression : 483/885 | OK
Progression : 484/885 | OK
Progression : 485/885 | OK
Progression : 486/885 | OK
Progression : 487/885 | OK
Progression : 488/885 | OK
Progression : 489/885 | OK
Progression : 490/885 | OK
Progression : 491/885 | OK
Progression : 492/885 | OK
Progression : 493/885 | OK
Progression : 494/885 | OK
Progression : 495/885 | OK
Progression : 496/885 | OK
Progression : 497/885 | OK
Progression : 498/885 | OK
Progression : 499/885 | OK
Progression : 500/885 | OK
Progression : 501/885 | OK
Progression : 502/885 | OK
Progression : 503/885 | OK
Progression : 504/885 | OK
Progression : 505/885 | OK
Progression : 506/885 | OK
Progression : 507/885 | OK
Progression : 508/885 | OK
Progression : 509/885 | OK
Progression : 510/885 | OK
Progression : 511/885 | OK
Progression : 512/885 | OK
Progression : 513/885 | OK
Progression : 514/885 | OK
Progression : 515/885 | OK
Progression : 516/885 | OK
Progression : 517/885 | OK
Progression : 518/885 | OK
Progression : 519/885 | OK
Progression : 520/885 | OK
Progression : 521/885 | OK
Progression : 522/885 | OK
Progression : 523/885 | OK
Progression : 524/885 | OK
Progression : 525/885 | OK
Progression : 526/885 | OK
Progression : 527/885 | OK
Progression : 528/885 | OK
Progression : 529/885 | OK
Progression : 530/885 | OK
Progression : 531/885 | OK
Progression : 532/885 | OK
Progression : 533/885 | OK
Progression : 534/885 | OK
Progression : 535/885 | OK
Progression : 536/885 | OK
Progression : 537/885 | OK
Progression : 538/885 | OK
Progression : 539/885 | OK
Progression : 540/885 | OK
Progression : 541/885 | OK
Progression : 542/885 | OK
Progression : 543/885 | OK
Progression : 544/885 | OK
Progression : 545/885 | OK
Progression : 546/885 | OK
Progression : 547/885 | OK
Progression : 548/885 | OK
Progression : 549/885 | OK
Progression : 550/885 | OK
Progression : 551/885 | OK
Progression : 552/885 | OK
Progression : 553/885 | OK
Progression : 554/885 | OK
Progression : 555/885 | OK
Progression : 556/885 | OK
Progression : 557/885 | OK
Progression : 558/885 | OK
Progression : 559/885 | OK
Progression : 560/885 | OK
Progression : 561/885 | OK
Progression : 562/885 | OK
Progression : 563/885 | OK
Progression : 564/885 | OK
Progression : 565/885 | OK
Progression : 566/885 | OK
Progression : 567/885 | OK
Progression : 568/885 | OK
Progression : 569/885 | OK
Progression : 570/885 | OK
Progression : 571/885 | OK
Progression : 572/885 | OK
Progression : 573/885 | OK
Progression : 574/885 | OK
Progression : 575/885 | OK
Progression : 576/885 | OK
Progression : 577/885 | OK
Progression : 578/885 | OK
Progression : 579/885 | OK
Progression : 580/885 | OK
Progression : 581/885 | OK
Progression : 582/885 | OK
Progression : 583/885 | OK
Progression : 584/885 | OK
Progression : 585/885 | OK
Progression : 586/885 | OK
Progression : 587/885 | OK
Progression : 588/885 | OK
Progression : 589/885 | OK
Progression : 590/885 | OK
Progression : 591/885 | OK
Progression : 592/885 | OK
Progression : 593/885 | Erreur 410
Progression : 594/885 | Erreur 410
Progression : 595/885 | Erreur 410
Progression : 596/885 | Erreur 410
Progression : 597/885 | OK
Progression : 598/885 | Erreur 410
Progression : 599/885 | Erreur 410
Progression : 600/885 | OK
Progression : 601/885 | Erreur 410
Progression : 602/885 | OK
Progression : 603/885 | Erreur 410
Progression : 604/885 | Erreur 410
Progression : 605/885 | OK
Progression : 606/885 | Erreur 410
Progression : 607/885 | Erreur 410
Progression : 608/885 | OK
Progression : 609/885 | Erreur 410
Progression : 610/885 | Erreur 410
Progression : 611/885 | Erreur 410
Progression : 612/885 | OK
Progression : 613/885 | Erreur 410
Progression : 614/885 | Erreur 410
Progression : 615/885 | Erreur 410
Progression : 616/885 | Erreur 410
Progression : 617/885 | OK
Progression : 618/885 | Erreur 410
Progression : 619/885 | Erreur 410
Progression : 620/885 | Erreur 410
Progression : 621/885 | Erreur 410
Progression : 622/885 | OK
Progression : 623/885 | Erreur 410
Progression : 624/885 | Erreur 410
Progression : 625/885 | Erreur 410
Progression : 626/885 | OK
Progression : 627/885 | OK
Progression : 628/885 | OK
Progression : 629/885 | OK
Progression : 630/885 | Erreur 410
Progression : 631/885 | Erreur 410
Progression : 632/885 | Erreur 410
Progression : 633/885 | OK
Progression : 634/885 | Erreur 410
Progression : 635/885 | Erreur 410
Progression : 636/885 | Erreur 410
Progression : 637/885 | OK
Progression : 638/885 | Erreur 410
Progression : 639/885 | Erreur 410
Progression : 640/885 | OK
Progression : 641/885 | OK
Progression : 642/885 | Erreur 410
Progression : 643/885 | OK
Progression : 644/885 | Erreur 410
Progression : 645/885 | Erreur 410
Progression : 646/885 | OK
Progression : 647/885 | Erreur 410
Progression : 648/885 | Erreur 410
Progression : 649/885 | OK
Progression : 650/885 | OK
Progression : 651/885 | OK
Progression : 652/885 | OK
Progression : 653/885 | OK
Progression : 654/885 | Erreur 410
Progression : 655/885 | Erreur 410
Progression : 656/885 | Erreur 410
Progression : 657/885 | Erreur 410
Progression : 658/885 | Erreur 410
Progression : 659/885 | OK
Progression : 660/885 | Erreur 410
Progression : 661/885 | OK
Progression : 662/885 | Erreur 410
Progression : 663/885 | Erreur 410
Progression : 664/885 | Erreur 410
Progression : 665/885 | OK
Progression : 666/885 | Erreur 410
Progression : 667/885 | Erreur 410
Progression : 668/885 | Erreur 410
Progression : 669/885 | Erreur 410
Progression : 670/885 | Erreur 410
Progression : 671/885 | Erreur 410
Progression : 672/885 | Erreur 410
Progression : 673/885 | OK
Progression : 674/885 | Erreur 410
Progression : 675/885 | OK
Progression : 676/885 | Erreur 410
Progression : 677/885 | Erreur 410
Progression : 678/885 | OK
Progression : 679/885 | OK
Progression : 680/885 | Erreur 410

,url,Titre,Date de publication,ID,Ville,Pays,Texte,Lien Original
0,https://orange.jobs/fr/fr/job/CTS-2025-47627/S...,Stage – IA appliquée : assistant automatique d...,2026-01-20,CTS-2025-47627,CHÂTILLON,FRANCE,&lt;p&gt;&lt;strong&gt;Date de publication :&l...,https://orange.jobs/fr/fr/job/CTS-2025-47627/S...
1,https://orange.jobs/fr/fr/job/CTS-2025-45465/C...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://orange.jobs/fr/fr/job/CTS-2025-43229/O...,Offre de stage orange Madagascar F/H,2026-01-20,CTS-2025-43229,ANTANANARIVO,MADAGASCAR,&lt;p&gt;&lt;strong&gt;Date de publication :&l...,https://orange.jobs/fr/fr/job/CTS-2025-43229/O...
3,https://orange.jobs/fr/fr/job/CTS-2025-46623/I...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://orange.jobs/fr/fr/job/CTS-2023-26884/S...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
orange_jobs_full.dropna(inplace=True)
print(f"Offres après nettoyage : {len(orange_jobs_full)}")
orange_jobs_full.drop('Lien Original', axis=1, inplace=True)
orange_jobs_full.head()

Offres après nettoyage : 542

,url,Titre,Date de publication,ID,Ville,Pays,Texte
0,https://orange.jobs/fr/fr/job/CTS-2025-47627/S...,Stage – IA appliquée : assistant automatique d...,2026-01-20,CTS-2025-47627,CHÂTILLON,FRANCE,&lt;p&gt;&lt;strong&gt;Date de publication :&l...
2,https://orange.jobs/fr/fr/job/CTS-2025-43229/O...,Offre de stage orange Madagascar F/H,2026-01-20,CTS-2025-43229,ANTANANARIVO,MADAGASCAR,&lt;p&gt;&lt;strong&gt;Date de publication :&l...
5,https://orange.jobs/fr/fr/job/CTS-2025-47360/S...,Stagiaire Ingénieur/Ingénieure - Développement...,2026-01-20,CTS-2025-47360,CAEN,FRANCE,&lt;p&gt;&lt;strong&gt;Date de publication :&l...
8,https://orange.jobs/fr/fr/job/CTS-2025-46612/S...,Stage – Ingénieur.e chercheur.euse IA agentique,2026-01-20,CTS-2025-46612,CAEN,FRANCE,&lt;p&gt;&lt;strong&gt;Date de publication :&l...
12,https://orange.jobs/fr/fr/job/CTS-2025-47055/C...,CDD - Gestionnaire Transports/logistique F/H,2026-01-20,CTS-2025-47055,BREST,FRANCE,&lt;p&gt;&lt;strong&gt;Date de publication :&l...

In [30]:
# Filtrer pour garder uniquement les offres de stage
orange_jobs_stages = orange_jobs_full[orange_jobs_full['Titre'].str.match(r'^Stage', case=False, na=False)]
print(f"Offres de stage trouvées : {len(orange_jobs_stages)} / {len(orange_jobs_full)}")
orange_jobs_stages.head(10)

Offres de stage trouvées : 34 / 542

,url,Titre,Date de publication,ID,Ville,Pays,Texte,Lien Original
0,https://orange.jobs/fr/fr/job/CTS-2025-47627/S...,Stage – IA appliquée : assistant automatique d...,2026-01-20,CTS-2025-47627,CHÂTILLON,FRANCE,&lt;p&gt;&lt;strong&gt;Date de publication :&l...,https://orange.jobs/fr/fr/job/CTS-2025-47627/S...
8,https://orange.jobs/fr/fr/job/CTS-2025-46612/S...,Stage – Ingénieur.e chercheur.euse IA agentique,2026-01-20,CTS-2025-46612,CAEN,FRANCE,&lt;p&gt;&lt;strong&gt;Date de publication :&l...,https://orange.jobs/fr/fr/job/CTS-2025-46612/S...
15,https://orange.jobs/fr/fr/job/CTS-2025-47606/S...,Stage en Communication et Valorisation de l'In...,2026-01-20,CTS-2025-47606,CHÂTILLON,FRANCE,&lt;p&gt;&lt;strong&gt;Date de publication :&l...,https://orange.jobs/fr/fr/job/CTS-2025-47606/S...
17,https://orange.jobs/fr/fr/job/CTS-2024-40152/S...,Stage – Intégration d'un Agent IA aux Outils d...,2026-01-20,CTS-2024-40152,BLAGNAC,FRANCE,&lt;p&gt;&lt;strong&gt;Date de publication :&l...,https://orange.jobs/fr/fr/job/CTS-2024-40152/S...
25,https://orange.jobs/fr/fr/job/CTS-2025-47761/S...,Stage - Graphiste F/H,2026-01-20,CTS-2025-47761,NANTERRE,FRANCE,&lt;p&gt;&lt;strong&gt;Date de publication :&l...,https://orange.jobs/fr/fr/job/CTS-2025-47761/S...
37,https://orange.jobs/fr/fr/job/CTS-2025-46917/S...,Stage Marketing - Chef de Produit Junior - Mob...,2026-01-20,CTS-2025-46917,ARCUEIL,FRANCE,&lt;p&gt;&lt;strong&gt;Date de publication :&l...,https://orange.jobs/fr/fr/job/CTS-2025-46917/S...
39,https://orange.jobs/fr/fr/job/CTS-2025-47923/S...,Stage en sociologie sur les usages de robots c...,2026-01-20,CTS-2025-47923,CHÂTILLON,FRANCE,&lt;p&gt;&lt;strong&gt;Date de publication :&l...,https://orange.jobs/fr/fr/job/CTS-2025-47923/S...
40,https://orange.jobs/fr/fr/job/CTS-2025-47287/S...,Stage - Chargé(e) du Projet de Culture Orange F/H,2026-01-20,CTS-2025-47287,ISSY-LES-MOULINEAUX,FRANCE,&lt;p&gt;&lt;strong&gt;Date de publication :&l...,https://orange.jobs/fr/fr/job/CTS-2025-47287/S...
51,https://orange.jobs/fr/fr/job/CTS-2025-47748/S...,Stage - Product Owner expérience digitale clie...,2026-01-20,CTS-2025-47748,ARCUEIL,FRANCE,&lt;p&gt;&lt;strong&gt;Date de publication :&l...,https://orange.jobs/fr/fr/job/CTS-2025-47748/S...
65,https://orange.jobs/fr/fr/job/CTS-2026-48927/S...,Stage - Chargé de Marketing opérationnel et co...,2026-01-20,CTS-2026-48927,NANTERRE,FRANCE,&lt;p&gt;&lt;strong&gt;Date de publication :&l...,https://orange.jobs/fr/fr/job/CTS-2026-48927/S...

In [ ]:
orange_jobs_stages.to_csv('offres/orange_jobs_stages.csv', index=False, encoding='utf-8')

## Scraping L'oreal

In [34]:
def get_loreal_links_only():
    base_url = "https://careers.loreal.com/fr_FR/jobs/SearchJobsAJAX/"
    
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "X-Requested-With": "XMLHttpRequest"
    }

    job_links = []
    offset = 0
    step = 20 # Pagination par 20
    
    print("--- Phase 1 : Collecte des liens (Stages) ---")

    while True:
        # Filtre 3_33_3=135 (Stages) + Pagination
        params = {
            "3_33_3": "135",
            "jobOffset": offset
        }

        try:
            print(f"Scraping page (offset {offset})...", end="")
            response = requests.get(base_url, headers=headers, params=params)
            
            # Gestion du format de réponse (JSON contenant du HTML ou HTML direct)
            try:
                data = response.json()
                html_source = data.get('content') or data.get('html') or response.text
            except:
                html_source = response.text

            soup = BeautifulSoup(html_source, 'html.parser')
            
            # On cible les articles
            articles = soup.find_all('article', class_='article--result')
            
            if not articles:
                print(" -> Aucun résultat. Fin de la collecte.")
                break

            count_page = 0
            for article in articles:
                # On cherche le lien dans le titre h3 > a
                h3 = article.find('h3', class_='article__header__text__title')
                if h3:
                    a_tag = h3.find('a')
                    if a_tag and 'href' in a_tag.attrs:
                        link = a_tag['href']
                        job_links.append(link)
                        count_page += 1
            
            print(f" -> {count_page} liens trouvés.")
            
            # Si on trouve moins de 20 liens, c'est que c'est la dernière page
            if len(articles) < step:
                print("Dernière page atteinte.")
                break

            offset += step
            time.sleep(1) # Pause courte

        except Exception as e:
            print(f"\nErreur : {e}")
            break

    return job_links

# --- Exécution ---
loreal_job_urls = get_loreal_links_only()

# Créer un DataFrame avec les URLs
loreal_jobs_df = pd.DataFrame({'url': loreal_job_urls})

print(f"\n--- Bilan ---")
print(f"Nombre d'offres uniques trouvées : {len(loreal_jobs_df)}")
print(f"\nDataFrame créé :")
loreal_jobs_df.head(10)

--- Phase 1 : Collecte des liens (Stages) ---
Scraping page (offset 0)... -> 20 liens trouvés.
Scraping page (offset 20)... -> 20 liens trouvés.
Scraping page (offset 40)... -> 20 liens trouvés.
Scraping page (offset 60)... -> 20 liens trouvés.
Scraping page (offset 80)... -> 20 liens trouvés.
Scraping page (offset 100)... -> 20 liens trouvés.
Scraping page (offset 120)... -> 20 liens trouvés.
Scraping page (offset 140)... -> 10 liens trouvés.
Dernière page atteinte.

--- Bilan ---
Nombre d'offres uniques trouvées : 150

DataFrame créé :

                                                 url
0  https://careers.loreal.com/fr_FR/jobs/JobDetai...
1  https://careers.loreal.com/fr_FR/jobs/JobDetai...
2  https://careers.loreal.com/fr_FR/jobs/JobDetai...
3  https://careers.loreal.com/fr_FR/jobs/JobDetai...
4  https://careers.loreal.com/fr_FR/jobs/JobDetai...
5  https://careers.loreal.com/fr_FR/jobs/JobDetai...
6  https://careers.loreal.com/fr_FR/jobs/JobDetai...
7  https://careers.loreal.com/fr_FR/jobs/JobDetai...
8  https://careers.loreal.com/fr_FR/jobs/JobDetai...
9  https://careers.loreal.com/fr_FR/jobs/JobDetai...

In [35]:
loreal_jobs_df.to_csv('loreal_jobs_stages_links.csv', index=False, encoding='utf-8')

In [37]:
import re

def get_job_date_robust(url):
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    }
    
    try:
        response = requests.get(url, headers=headers)
        soup = BeautifulSoup(response.text, 'html.parser')
        
        # --- MÉTHODE 1 : JSON-LD (La pépite pour Google Jobs) ---
        json_scripts = soup.find_all('script', type='application/ld+json')
        for script in json_scripts:
            try:
                data = json.loads(script.string)
                if data.get('@type') == 'JobPosting' and 'datePosted' in data:
                    return data['datePosted']
            except:
                continue

        # --- MÉTHODE 2 : Les Meta Tags ---
        meta_date = soup.find('meta', property='article:published_time') or \
                    soup.find('meta', itemprop='datePosted') or \
                    soup.find('meta', attrs={"name": "dcterms.created"})
        
        if meta_date and meta_date.get('content'):
            return meta_date['content']

        # --- MÉTHODE 3 : Recherche de texte brut ---
        text_content = soup.get_text()
        match = re.search(r'(Publié|Posted)\s+(:|le|on)?\s*(\d{1,2}[-/\s]\w{3,10}[-/\s]\d{4})', text_content, re.IGNORECASE)
        
        if match:
            return match.group(3)

        return "Date introuvable"

    except Exception as e:
        return f"Erreur: {e}"

def scrap_loreal_details(url):
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    }

    try:
        response = requests.get(url, headers=headers)
        if response.status_code != 200:
            return f"Erreur {response.status_code}"

        soup = BeautifulSoup(response.text, 'html.parser')
        
        info_job = {}

        # --- ÉTAPE 1 : Extraction via le DataLayer ---
        script_content = ""
        for script in soup.find_all('script'):
            if script.string and "dataLayer.push" in script.string and "jobIDATS" in script.string:
                script_content = script.string
                break
        
        if script_content:
            def get_js_var(key, text):
                pattern = re.compile(rf'{key}:\s*"([^"]+)"')
                match = pattern.search(text)
                return match.group(1) if match else "Non trouvé"

            info_job["Titre"] = get_js_var("jobTitle", script_content)
            info_job["Ville"] = get_js_var("jobLocation", script_content)
            info_job["Pays"] = get_js_var("jobCountry", script_content)
            info_job["ID"] = get_js_var("jobIDATS", script_content)
            info_job["Type"] = get_js_var("jobPositionType", script_content)

        # --- ÉTAPE 2 : Extraction de la Date (Méthode robuste) ---
        info_job["Date de publication"] = get_job_date_robust(url)

        # --- ÉTAPE 3 : Extraction du Texte de l'offre ---
        description_div = soup.find('div', class_='article__content')
        if not description_div:
            description_div = soup.find('div', class_='job-description')
        
        if description_div:
            info_job["Texte de l'offre"] = description_div.get_text(separator='\n').strip()
        else:
            info_job["Texte de l'offre"] = "Description introuvable"

        return info_job

    except Exception as e:
        return f"Erreur critique : {e}"

# --- TEST ---
url_test = "https://careers.loreal.com/fr_FR/jobs/JobDetail/Trade-Marketing-Trainee-L-Or-al-Dermatological-Beauty-Espoo-FI/198643"
details = scrap_loreal_details(url_test)

print("--- RÉSULTATS ---")
for k, v in details.items():
    if k == "Texte de l'offre":
        print(f"{k} : {v[:200]} [...]")
    else:
        print(f"{k} : {v}")

--- RÉSULTATS ---
Titre : Trade Marketing Trainee - L'Oréal Dermatological Beauty - Espoo (FI)
Ville : Espoo, Southwest Finland
Pays : Finland
ID : 198643
Type : Stage
Date de publication : 2025-02-12
Texte de l'offre : Stage








                                                                                            Southwest  [...]

In [38]:
import time
import random

# Appliquer le scraping sur toutes les offres L'oreal et enrichir le DataFrame
job_rows = []
errors = []
total = len(loreal_jobs_df)
print(f"Début du scraping L'oreal : {total} offres")

for idx, url in enumerate(loreal_jobs_df['url'], start=1):
    info = scrap_loreal_details(url)
    if isinstance(info, dict):
        info['url'] = url  # conserver la clé de jointure
        job_rows.append(info)
        status_msg = "OK"
    else:
        errors.append({'url': url, 'erreur': info})
        if isinstance(info, str) and '410' in info:
            status_msg = "Erreur 410"
        else:
            status_msg = f"Erreur: {info}"
            print(f"Erreur de scraping pour {url} -> {info}")
    
    print(f"Progression : {idx}/{total} | {status_msg}")

    time.sleep(random.uniform(1, 3))

loreal_jobs_details = pd.DataFrame(job_rows)
loreal_jobs_full = loreal_jobs_df.merge(loreal_jobs_details, on='url', how='left')

print(f"\nOffres enrichies : {len(loreal_jobs_details)} / {len(loreal_jobs_df)}")
print(f"Erreurs : {len(errors)}")
loreal_jobs_full.head()

Début du scraping L'oreal : 150 offres
Progression : 1/150 | OK
Progression : 2/150 | OK
Progression : 3/150 | OK
Progression : 4/150 | OK
Progression : 5/150 | OK
Progression : 6/150 | OK
Progression : 7/150 | OK
Progression : 8/150 | OK
Progression : 9/150 | OK
Progression : 10/150 | OK
Progression : 11/150 | OK
Progression : 12/150 | OK
Progression : 13/150 | OK
Progression : 14/150 | OK
Progression : 15/150 | OK
Progression : 16/150 | OK
Progression : 17/150 | OK
Progression : 18/150 | OK
Progression : 19/150 | OK
Progression : 20/150 | OK
Progression : 21/150 | OK
Progression : 22/150 | OK
Progression : 23/150 | OK
Progression : 24/150 | OK
Progression : 25/150 | OK
Progression : 26/150 | OK
Progression : 27/150 | OK
Progression : 28/150 | OK
Progression : 29/150 | OK
Progression : 30/150 | OK
Progression : 31/150 | OK
Progression : 32/150 | OK
Progression : 33/150 | OK
Progression : 34/150 | OK
Progression : 35/150 | OK
Progression : 36/150 | OK
Progression : 37/150 | OK
Progression : 38/150 | OK
Progression : 39/150 | OK
Progression : 40/150 | OK
Progression : 41/150 | OK
Progression : 42/150 | OK
Progression : 43/150 | OK
Progression : 44/150 | OK
Progression : 45/150 | OK
Progression : 46/150 | OK
Progression : 47/150 | OK
Progression : 48/150 | OK
Progression : 49/150 | OK
Progression : 50/150 | OK
Progression : 51/150 | OK
Progression : 52/150 | OK
Progression : 53/150 | OK
Progression : 54/150 | OK
Progression : 55/150 | OK
Progression : 56/150 | OK
Progression : 57/150 | OK
Progression : 58/150 | OK
Progression : 59/150 | OK
Progression : 60/150 | OK
Progression : 61/150 | OK
Progression : 62/150 | OK
Progression : 63/150 | OK
Progression : 64/150 | OK
Progression : 65/150 | OK
Progression : 66/150 | OK
Progression : 67/150 | OK
Progression : 68/150 | OK
Progression : 69/150 | OK
Progression : 70/150 | OK
Progression : 71/150 | OK
Progression : 72/150 | OK
Progression : 73/150 | OK
Progression : 74/150 | OK
Progression : 75/150 | OK
Progression : 76/150 | OK
Progression : 77/150 | OK
Progression : 78/150 | OK
Progression : 79/150 | OK
Progression : 80/150 | OK
Progression : 81/150 | OK
Progression : 82/150 | OK
Progression : 83/150 | OK
Progression : 84/150 | OK
Progression : 85/150 | OK
Progression : 86/150 | OK
Progression : 87/150 | OK
Progression : 88/150 | OK
Progression : 89/150 | OK
Progression : 90/150 | OK
Progression : 91/150 | OK
Progression : 92/150 | OK
Progression : 93/150 | OK
Progression : 94/150 | OK
Progression : 95/150 | OK
Progression : 96/150 | OK
Progression : 97/150 | OK
Progression : 98/150 | OK
Progression : 99/150 | OK
Progression : 100/150 | OK
Progression : 101/150 | OK
Progression : 102/150 | OK
Progression : 103/150 | OK
Progression : 104/150 | OK
Progression : 105/150 | OK
Progression : 106/150 | OK
Progression : 107/150 | OK
Progression : 108/150 | OK
Progression : 109/150 | OK
Progression : 110/150 | OK
Progression : 111/150 | OK
Progression : 112/150 | OK
Progression : 113/150 | OK
Progression : 114/150 | OK
Progression : 115/150 | OK
Progression : 116/150 | OK
Progression : 117/150 | OK
Progression : 118/150 | OK
Progression : 119/150 | OK
Progression : 120/150 | OK
Progression : 121/150 | OK
Progression : 122/150 | OK
Progression : 123/150 | OK
Progression : 124/150 | OK
Progression : 125/150 | OK
Progression : 126/150 | OK
Progression : 127/150 | OK
Progression : 128/150 | OK
Progression : 129/150 | OK
Progression : 130/150 | OK
Progression : 131/150 | OK
Progression : 132/150 | OK
Progression : 133/150 | OK
Progression : 134/150 | OK
Progression : 135/150 | OK
Progression : 136/150 | OK
Progression : 137/150 | OK
Progression : 138/150 | OK
Progression : 139/150 | OK
Progression : 140/150 | OK
Progression : 141/150 | OK
Progression : 142/150 | OK
Progression : 143/150 | OK
Progression : 144/150 | OK
Progression : 145/150 | OK
Progression : 146/150 | OK
Progression : 147/150 | OK
Progression : 148/150 | OK
Progression : 149/150 | OK
Progression : 150/150 | OK

Offres enrichies : 150 / 150
Erreurs : 0

,url,Titre,Ville,Pays,ID,Type,Date de publication,Texte de l'offre
0,https://careers.loreal.com/fr_FR/jobs/JobDetai...,Trade Marketing Trainee - L'Oréal Dermatologic...,"Espoo, Southwest Finland",Finland,198643,Stage,2025-02-12,Stage\n ...
1,https://careers.loreal.com/fr_FR/jobs/JobDetai...,Internship Marketing (Paid) - Per February 2026,"Hoofddorp, North Holland",Netherlands,217197,Stage,2025-09-03,Stage\n ...
2,https://careers.loreal.com/fr_FR/jobs/JobDetai...,Stage Ingénieur Assurance Qualité (H/F),"Libramont, Wallonia",Belgium,223156,Stage,2025-04-09,Stage\n ...
3,https://careers.loreal.com/fr_FR/jobs/JobDetai...,PRAKTIKUM (M/W/D) Human Resources - Start März...,"Vienna, Vienna",Austria,217313,Stage,2025-09-04,Stage\n ...
4,https://careers.loreal.com/fr_FR/jobs/JobDetai...,Digital Data Internship,"Prague, Praha",Czech Republic,227812,Stage,2025-12-12,Stage\n ...

In [39]:
# Nettoyage et filtrage des offres L'oreal
loreal_jobs_full.dropna(inplace=True)
# garder uniquement les offres de stage en France avec la colonne pays 
loreal_jobs_full = loreal_jobs_full[(loreal_jobs_full['Pays'].str.lower() == 'france')]
print(f"Offres après nettoyage : {len(loreal_jobs_full)}")
loreal_jobs_full.head()

Offres après nettoyage : 67

,url,Titre,Ville,Pays,ID,Type,Date de publication,Texte de l'offre
35,https://careers.loreal.com/fr_FR/jobs/JobDetai...,Stage de 3 mois minimum - À partir de Janvier ...,"Pau, Aquitaine-Limousin-Poitou-Charentes",France,223831,Stage,2025-10-30,Stage\n ...
36,https://careers.loreal.com/fr_FR/jobs/JobDetai...,Stage de 6 mois - Ingénieur(e) EHS Santé Sécur...,"Pau, Aquitaine-Limousin-Poitou-Charentes",France,226736,Stage,2025-12-01,Stage\n ...
70,https://careers.loreal.com/fr_FR/jobs/JobDetai...,STAGE 6 MOIS - À PARTIR DÉBUT MARS 2026 - Ingé...,"Aulnay-sous-Bois, Île-de-France",France,221392,Stage,2026-03-02,Stage\n ...
71,https://careers.loreal.com/fr_FR/jobs/JobDetai...,STAGE 6 MOIS - À partir de mars 2026 – Flux QH...,"Cambrai, Nord-Pas-de-Calais-Picardie",France,218042,Stage,2026-02-03,Stage\n ...
72,https://careers.loreal.com/fr_FR/jobs/JobDetai...,STAGE 6 MOIS - À partir de janvier 2026 – Perf...,"Cambrai, Nord-Pas-de-Calais-Picardie",France,218040,Stage,2026-01-26,Stage\n ...

In [42]:
# Nettoyer la colonne Ville pour garder uniquement la ville
loreal_jobs_stages = loreal_jobs_full.copy()
loreal_jobs_stages['Ville'] = loreal_jobs_stages['Ville'].str.split(',').str[0].str.strip()

print("Villes nettoyées !")
print("\nExemples L'oreal :")
print(loreal_jobs_stages[['Titre', 'Ville']].head())

Villes nettoyées !

Exemples L'oreal :
                                                Titre             Ville
35  Stage de 3 mois minimum - À partir de Janvier ...               Pau
36  Stage de 6 mois - Ingénieur(e) EHS Santé Sécur...               Pau
70  STAGE 6 MOIS - À PARTIR DÉBUT MARS 2026 - Ingé...  Aulnay-sous-Bois
71  STAGE 6 MOIS - À partir de mars 2026 – Flux QH...           Cambrai
72  STAGE 6 MOIS - À partir de janvier 2026 – Perf...           Cambrai

In [44]:
loreal_jobs_stages.head(10)

,url,Titre,Ville,Pays,ID,Type,Date de publication,Texte de l'offre
35,https://careers.loreal.com/fr_FR/jobs/JobDetai...,Stage de 3 mois minimum - À partir de Janvier ...,Pau,France,223831,Stage,2025-10-30,Stage\n ...
36,https://careers.loreal.com/fr_FR/jobs/JobDetai...,Stage de 6 mois - Ingénieur(e) EHS Santé Sécur...,Pau,France,226736,Stage,2025-12-01,Stage\n ...
70,https://careers.loreal.com/fr_FR/jobs/JobDetai...,STAGE 6 MOIS - À PARTIR DÉBUT MARS 2026 - Ingé...,Aulnay-sous-Bois,France,221392,Stage,2026-03-02,Stage\n ...
71,https://careers.loreal.com/fr_FR/jobs/JobDetai...,STAGE 6 MOIS - À partir de mars 2026 – Flux QH...,Cambrai,France,218042,Stage,2026-02-03,Stage\n ...
72,https://careers.loreal.com/fr_FR/jobs/JobDetai...,STAGE 6 MOIS - À partir de janvier 2026 – Perf...,Cambrai,France,218040,Stage,2026-01-26,Stage\n ...
73,https://careers.loreal.com/fr_FR/jobs/JobDetai...,STAGE 6 MOIS - À partir de avril 2026 – Perfor...,Cambrai,France,225232,Stage,2026-01-12,Stage\n ...
74,https://careers.loreal.com/fr_FR/jobs/JobDetai...,STAGE 6 MOIS - À partir de janvier 2026 – Qual...,Cambrai,France,218068,Stage,2026-01-05,Stage\n ...
90,https://careers.loreal.com/fr_FR/jobs/JobDetai...,STAGE DE 6 MOIS - A partir de janvier/février ...,Rambouillet,France,224557,Stage,2025-12-01,Stage\n ...
91,https://careers.loreal.com/fr_FR/jobs/JobDetai...,Stagiaire Amélioration Continue et Digitalisat...,Aulnay-sous-Bois,France,215574,Stage,2025-10-01,Stage\n ...
92,https://careers.loreal.com/fr_FR/jobs/JobDetai...,STAGE 6 MOIS - À partir de février 2026 – Supp...,FR - Roye,France,219418,Stage,2026-02-01,Stage\n ...

In [ ]:
# Enregistrer les offres de stage L'oreal en CSV
loreal_jobs_stages.to_csv('offres/loreal_jobs_stages.csv', index=False, encoding='utf-8')
print("Fichier 'loreal_jobs_stages.csv' créé avec succès!")

Fichier 'loreal_jobs_stages.csv' créé avec succès!

In [3]:
orange = pd.read_csv('offres/orange_jobs_stages.csv', encoding='utf-8')
loreal = pd.read_csv('offres/loreal_jobs_stages.csv', encoding='utf-8')

orange['entreprise'] = 'Orange'
loreal['entreprise'] = 'L\'Oréal'

orange.to_csv('offres/orange_jobs_stages.csv', index=False, encoding='utf-8')
loreal.to_csv('offres/loreal_jobs_stages.csv', index=False, encoding='utf-8')