# WebScraping offre de stage 
Entreprise à faire : 
* Naval groupe
* SNCF 
* EDF / ENEDIS

# Naval groupe

In [21]:
from bs4 import BeautifulSoup
import requests as req
import pandas as pd
import time

base_url = "https://www.naval-group.com"
# URL de recherche de base (sans le #offer-list-content pour éviter les erreurs de paramètre)
search_url = "https://www.naval-group.com/fr/nous-rejoindre?keywords=&offerFamilyCategory=&contractType=2463&country=&city=&op=Rechercher&form_build_id=form-iVE3g9N2r4Nu7lu3KCGc60KTmI_QK7gNmDva38VhQec&form_id=talent_soft_offers_filters_form"

all_offers_data = []
page_number = 0

while True:
    #pour test 
    if page_number >= 10:
        break
    print(f"Traitement de la page {page_number}...")
    
    # Ajout du paramètre de pagination
    current_url = f"{search_url}&page={page_number}"
    
    response = req.get(current_url)
    soup = BeautifulSoup(response.content, 'html.parser')
    
    # Récupérer toutes les offres de la page courante
    job_offers = soup.find_all('div', class_='job-offer-item')
    
    # Si la liste est vide, on arrête la boucle (fin de la pagination)
    if not job_offers:
        print("Aucune offre trouvée, fin du scraping.")
        break
        
    for offer in job_offers:
        try:
            # Extraction des infos de la liste
            title = offer.find('h3', class_='job-offer-item-title').get_text(strip=True)
            category = offer.find('p', class_='job-offer-item-category').get_text(strip=True)
            relative_link = offer.find('a', class_='btn-secondary')['href']
            full_link = base_url + relative_link
            
            # Extraction de la description (Requête supplémentaire vers la page de détail)
            resp_detail = req.get(full_link)
            soup_detail = BeautifulSoup(resp_detail.content, 'html.parser')
            desc_block = soup_detail.find(class_='layout-sidebar-left')
            description = desc_block.get_text(separator='\n', strip=True) if desc_block else "Pas de description"
            
            # Ajout au dictionnaire
            all_offers_data.append({
                "Titre": title,
                "Catégorie": category,
                "Lien": full_link,
                "Description": description
            })
            
        except Exception as e:
            print(f"Erreur lors du traitement d'une offre : {e}")
            continue

    page_number += 1
    time.sleep(0.5) # Petite pause pour être poli envers le serveur

# Création du DataFrame final
df = pd.DataFrame(all_offers_data)

# Affichage des premières lignes
df.head()

Traitement de la page 0...
Traitement de la page 1...
Traitement de la page 2...
Traitement de la page 3...
Traitement de la page 4...
Traitement de la page 5...
Traitement de la page 6...
Traitement de la page 7...
Traitement de la page 8...
Traitement de la page 9...

,Titre,Catégorie,Lien,Description
0,Stage - Business Analyst PLM - Domaine fonctio...,Digital,https://www.naval-group.com/fr/talents/offer/2...,Organisation\nNAVAL GROUP\nNous sommes un acte...
1,Stage – Ingénieur - Concepteur Environnement D...,Digital,https://www.naval-group.com/fr/talents/offer/2...,Organisation\nNAVAL GROUP\nNous sommes un acte...
2,Stage - Partenaire RH - H/F,RH,https://www.naval-group.com/fr/talents/offer/2...,Organisation\nNAVAL GROUP\nNous sommes un acte...
3,Stage- Ingénieur Développement Logiciel - H/F,Digital,https://www.naval-group.com/fr/talents/offer/2...,Organisation\nNAVAL GROUP\nNous sommes un acte...
4,Stage - Chargé de Relations Sociales - H/F,RH,https://www.naval-group.com/fr/talents/offer/2...,Organisation\nNAVAL GROUP\nNous sommes un acte...

In [22]:
df.head(10)

,Titre,Catégorie,Lien,Description
0,Stage - Business Analyst PLM - Domaine fonctio...,Digital,https://www.naval-group.com/fr/talents/offer/2...,Organisation\nNAVAL GROUP\nNous sommes un acte...
1,Stage – Ingénieur - Concepteur Environnement D...,Digital,https://www.naval-group.com/fr/talents/offer/2...,Organisation\nNAVAL GROUP\nNous sommes un acte...
2,Stage - Partenaire RH - H/F,RH,https://www.naval-group.com/fr/talents/offer/2...,Organisation\nNAVAL GROUP\nNous sommes un acte...
3,Stage- Ingénieur Développement Logiciel - H/F,Digital,https://www.naval-group.com/fr/talents/offer/2...,Organisation\nNAVAL GROUP\nNous sommes un acte...
4,Stage - Chargé de Relations Sociales - H/F,RH,https://www.naval-group.com/fr/talents/offer/2...,Organisation\nNAVAL GROUP\nNous sommes un acte...
5,Stage – Ingénieur simulation fonctionnelle et ...,Etudes Ingénierie Plateforme et Infrastructure,https://www.naval-group.com/fr/talents/offer/2...,Organisation\nNAVAL GROUP\nNous sommes un acte...
6,Stage - Responsable industrialisation amont/gé...,Méthode et Industrialisation,https://www.naval-group.com/fr/talents/offer/2...,Organisation\nNAVAL GROUP\nNous sommes un acte...
7,Stage - Responsable management des opérations ...,Programmes & Offres Industrielles,https://www.naval-group.com/fr/talents/offer/2...,Organisation\nNAVAL GROUP\nNous sommes un acte...
8,Stage - Modélisation des effets du choc milita...,Pilotage maîtrise Technique et Innovation,https://www.naval-group.com/fr/talents/offer/2...,Organisation\nNAVAL GROUP\nNous sommes un acte...
9,Stage – Ingénieur - Modélisation Système Mécan...,Etudes Ingénierie Systèmes Embarqués,https://www.naval-group.com/fr/talents/offer/2...,Organisation\nNAVAL GROUP\nNous sommes un acte...